[package]
name = "protobuf-core"
version = "0.2.1"
edition = "2024"
description = "A primitive utility library for Protocol Buffers in Rust"
license = "Apache-2.0"
repository = "https://github.com/wada314/protobuf-core"
documentation = "https://docs.rs/protobuf-core/"
readme = "README.md"

[dependencies]
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.5"

[features]
default = ["read", "write"]
read = []
write = []
